[package]
name = "b49"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.5.0"
askama = "0.10"
toml = "0.5.9"
serde = "1.0.145"
serde_derive = "1.0.145"