[web]
user = "1"
password = "1"

[[plugin]]
name = "telegram"
api_key = "key1"
title = "ultradesuyo"

[[plugin]]
name = "telegram"
api_key = "key2"
title = "cooking"

[[plugin]]
name = "telegram"
api_key = "key2"
title = "allah"
[[plugin]]

name = "telegram"
api_key = "key2"
title = "ass"
